services:
  pingpong1:
    build: .
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - INSTANCE_NUM=1
  pingpong2:
    build: .
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - INSTANCE_NUM=2

